name: Electron Build and Release

on:
  push:
    branches: [ "master" ]  # Trigger on pushes to the master branch
  # Optional: Trigger on tags (for creating releases)
  # tag:
  #   - 'v*'

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}  # Use a matrix to build on multiple platforms

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest] # Build for Windows, macOS, and Linux

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'  # Use a specific Node.js version (adjust as needed)

    - name: Install Dependencies
      run: npm install

    - name: Build Application
      run: npm run build  # Use the 'build' script from your package.json

    - name: Upload Artifacts (Optional) # Useful for debugging or manual downloads
      uses: actions/upload-artifact@v4.3.1
      with:
        name: ${{ matrix.os }}-build
        path: build/  # The output directory specified in your package.json

    # --- Release Step (Optional, but Highly Recommended) ---
    - name: Create Release (on tag push)
      if: startsWith(github.ref, 'refs/tags/')  # Only run on tag pushes
      uses: softprops/action-gh-release@v1
      with:
        files: build/*  # Upload all files from the build directory
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false
